=== BartChris/kitodo-production/Kitodo-DataEditor/src/test/resources/ruleset.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 *
 * (c) Kitodo. Key to digital objects e. V. <contact@kitodo.org>
 *
 * This file is part of the Kitodo project.
 *
 * It is licensed under GNU General Public License version 3 or later.
 *
 * For the full copyright and license information, please read the
 * GPL3-License.txt file that was distributed with this source code.
 *
-->
<!--
    This file provides an XML Schema for the ruleset. It was derived from the
    Java classes for parsing the ruleset. The structure and naming follow the
    the Java classes.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:ruleset="http://names.kitodo.org/ruleset/v2"
           elementFormDefault="qualified"
           targetNamespace="http://names.kitodo.org/ruleset/v2">

    <xs:complexType name="AcquisitionStage">
        <xs:sequence>
            <xs:element name="setting" minOccurs="1" maxOccurs="unbounded" type="ruleset:Setting"/>
        </xs:sequence>
        <xs:attribute use="required" type="xs:string" name="name"/>
    </xs:complexType>

    <xs:complexType name="CodomainElement">
        <xs:attribute type="ruleset:Type" name="type"/>
        <xs:attribute type="xs:anyURI" name="namespace"/>
    </xs:complexType>

    <xs:complexType name="DeclarationElement">
        <xs:sequence>
            <xs:element name="division" minOccurs="1" maxOccurs="unbounded" type="ruleset:Division" />
            <xs:element name="key" minOccurs="0" maxOccurs="unbounded" type="ruleset:Key"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Division">
        <xs:sequence>
            <xs:element type="ruleset:Label" minOccurs="1" maxOccurs="unbounded" name="label"/>
            <xs:element type="ruleset:SubdivisionByDateElement" minOccurs="0" maxOccurs="1" name="subdivisionByDate"/>
        </xs:sequence>
        <xs:attribute use="required" type="xs:NMTOKEN" name="id"/>
        <xs:attribute type="xs:string" name="processTitle"/>
        <xs:attribute type="xs:NMTOKEN" name="dates"/>
        <xs:attribute type="xs:string" name="scheme"/>
    </xs:complexType>

    <xs:simpleType name="DomainAttribute">
        <xs:restriction base="xs:string">
            <xs:enumeration value="description"/>
            <xs:enumeration value="digitalProvenance"/>
            <xs:enumeration value="rights"/>
            <xs:enumeration value="source"/>
            <xs:enumeration value="technical"/>
            <xs:enumeration value="mets:div"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="EditingElement">
        <xs:sequence>
            <xs:element name="setting" minOccurs="0" maxOccurs="unbounded" type="ruleset:Setting"/>
            <xs:element name="acquisitionStage" minOccurs="0" maxOccurs="unbounded" type="ruleset:AcquisitionStage"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Key">
        <xs:sequence>
            <xs:element name="label" minOccurs="1" maxOccurs="unbounded" type="ruleset:Label"/>
            <xs:element name="codomain" minOccurs="0" maxOccurs="1" type="ruleset:CodomainElement"/>
            <xs:element name="option" minOccurs="0" maxOccurs="unbounded" type="ruleset:Option"/>
            <xs:element name="pattern" minOccurs="0" maxOccurs="1" type="xs:string"/>
            <xs:element name="preset" minOccurs="0" maxOccurs="unbounded" type="xs:string"/>
            <xs:element name="key" minOccurs="0" maxOccurs="unbounded" type="ruleset:Key"/>
        </xs:sequence>
        <xs:attribute use="required" type="xs:NMTOKEN" name="id"/>
        <xs:attribute type="ruleset:DomainAttribute" name="domain" default="description"/>
    </xs:complexType>

    <xs:complexType name="Label">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="lang"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:element name="namespace">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="option" minOccurs="0" maxOccurs="unbounded" type="ruleset:Option"/>
            </xs:sequence>
            <xs:attribute type="xs:anyURI" name="about"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="Option">
        <xs:sequence>
            <xs:element name="label" minOccurs="0" maxOccurs="unbounded" type="ruleset:Label"/>
        </xs:sequence>
        <xs:attribute use="required" type="xs:string" name="value"/>
    </xs:complexType>

    <xs:complexType name="Rule">
        <xs:sequence>
            <xs:element name="permit" minOccurs="0" maxOccurs="unbounded" type="ruleset:Rule"/>
        </xs:sequence>
        <xs:attribute type="xs:NMTOKEN" name="division"/>
        <xs:attribute type="xs:NMTOKEN" name="key"/>
        <xs:attribute type="xs:string" name="value"/>
        <xs:attribute type="xs:nonNegativeInteger" name="minOccurs"/>
        <xs:attribute type="xs:nonNegativeInteger" name="maxOccurs"/>
        <xs:attribute type="ruleset:Unspecified" name="unspecified"/>
    </xs:complexType>

    <xs:element name="ruleset">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="declaration" minOccurs="1" maxOccurs="1" type="ruleset:DeclarationElement"/>
                <xs:element name="correlation" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="restriction" minOccurs="1" maxOccurs="unbounded" type="ruleset:Rule"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="editing" minOccurs="0" maxOccurs="1" type="ruleset:EditingElement"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="lang"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="Setting">
        <xs:sequence>
            <xs:element name="setting" minOccurs="0" maxOccurs="unbounded" type="ruleset:Setting"/>
        </xs:sequence>
        <xs:attribute type="xs:NMTOKEN" name="key"/>
        <xs:attribute type="xs:boolean" name="alwaysShowing" default="false"/>
        <xs:attribute type="xs:boolean" name="editable" default="true"/>
        <xs:attribute type="xs:boolean" name="excluded" default="false"/>
        <xs:attribute type="xs:boolean" name="multiline" default="false"/>
    </xs:complexType>

    <xs:complexType name="SubdivisionByDateElement">
        <xs:sequence>
            <xs:element name="division" minOccurs="1" maxOccurs="unbounded" type="ruleset:Division"/>
        </xs:sequence>
        <xs:attribute name="yearBegin">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="--((0[1-9]|1[0-2])-([01][1-9]|10|2[0-8]))|((0[13-9]|1[0-2])-(29|30))|((0[13578]|1[0-2])-31)"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:simpleType name="Type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="anyURI"/>
            <xs:enumeration value="boolean"/>
            <xs:enumeration value="date"/>
            <xs:enumeration value="integer"/>
            <xs:enumeration value="string"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Unspecified">
        <xs:restriction base="xs:string">
            <xs:enumeration value="unrestricted"/>
            <xs:enumeration value="forbidden"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== BartChris/kitodo-production/Kitodo/src/test/resources/rulesets/ruleset_test.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
 *
 * (c) Kitodo. Key to digital objects e. V. <contact@kitodo.org>
 *
 * This file is part of the Kitodo project.
 *
 * It is licensed under GNU General Public License version 3 or later.
 *
 * For the full copyright and license information, please read the
 * GPL3-License.txt file that was distributed with this source code.
 *
-->
<ruleset xmlns="http://names.kitodo.org/ruleset/v2"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://names.kitodo.org/ruleset/v2 ../../../../../Kitodo-DataEditor/src/main/resources/ruleset.xsd">
    <declaration>
        <division id="Monograph" processTitle="TSL_ATS+'_'+CatalogIDDigital">
            <label>Monograph</label>
        </division>
        <division id="something">
            <label>Outline element</label>
        </division>
        <division id="ContainedWork" processTitle="TSL_ATS+'_'+CatalogIDDigital">
            <label>Beigef√ºgtes Werk</label>
        </division>
        <key id="TitleDocMain" domain="source">
            <label>HauptTitel</label>
        </key>
        <key id="TitleDocMainShort" domain="technical">
            <label>Haupttitel (Sortierung)</label>
        </key>
        <key id="TSL_ATS">
            <label>TSL/ATS</label>
        </key>
        <key id="CatalogIDDigital">
            <label>PPN (digital)</label>
        </key>
        <key id="CatalogIDSource" domain="source">
            <label>PPN (Vorlage)</label>
        </key>
        <key id="Person">
            <label>Person</label>
            <key id="Role">
                <label>Rolle</label>
                <option value="Author">
                    <label>Autor</label>
                </option>
            </key>
            <key id="FirstName">
                <label>Vorname</label>
            </key>
            <key id="LastName">
                <label>Nachname</label>
            </key>
        </key>
    </declaration>
    <correlation>
        <restriction key="Person">
            <permit key="Role" minOccurs="1" maxOccurs="1"/>
            <permit key="FirstName"/>
            <permit key="LastName"/>
        </restriction>

        <restriction division="Monograph" unspecified="forbidden">
            <permit division="Monograph"/>
            <permit key="TitleDocMain" minOccurs="1"/>
            <permit key="TitleDocMainShort" minOccurs="1"/>
            <permit key="CatalogIDDigital" minOccurs="1"/>
            <permit key="CatalogIDSource" minOccurs="1"/>
            <permit key="TSL_ATS"/>
            <permit key="Person">
                <permit key="Role" unspecified="forbidden">
                    <permit value="Author"/>
                </permit>
            </permit>
        </restriction>
        <restriction division="ContainedWork" unspecified="forbidden">
                <permit key="TitleDocMain" minOccurs="1"/>
                <permit key="TitleDocMainShort" minOccurs="1"/>
                <permit key="CatalogIDDigital" minOccurs="1"/>
            <permit key="CatalogIDSource" minOccurs="1"/>
            <permit key="TSL_ATS"/>
        </restriction>
    </correlation>
    <editing>
        <setting key="TSL_ATS" alwaysShowing="true"/>
        <setting key="Person" alwaysShowing="true">
            <setting key="FirstName" alwaysShowing="true"/>
            <setting key="LastName" alwaysShowing="true"/>
        </setting>
    </editing>
</ruleset>
